accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"^register/$",views.register,name='register'),
    url(r"^login/$",views.loginUser,name='login'),
    url(r"^logout/$",views.logoutUser,name='logout'),
    url(r"^profile/(?P<pk>\d+)/$",views.profile_page,name='profile'),
    url(r"^deluser/$",views.delete_user,name="deluser"),

    url(r"^profile_api/(?P<pk>\d+)/$",views.profile_api,name='profile_api')
]

bugtracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('search',views.search,name='search'),
    path('set',views.set,name="set"),
    path('changepass',views.changepass,name="changepass"),
    url(r"^accounts/",include('accounts.urls',namespace="accounts")),
    url(r"^projects/", include("projects.urls", namespace="projects")),
    url(r"^issues/",include("issues.urls", namespace="issues")),
    url(r"^chats/",include("chats.urls", namespace="chats")),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,include

app_name='Chats'

urlpatterns = [
	path('all/', views.all, name="all"),	
]

issues/urls.py
from django.conf.urls import url
from . import views

app_name='Issues'

urlpatterns = [
    url(r"^$", views.IssueList.as_view(), name="all"),
    url(r"new/$", views.CreateIssue.as_view(), name="create"),
    url(r"by/(?P<pk>\d+)/$",views.IssueDetail,name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteIssue.as_view(),name="delete"),
    url(r"join/(?P<pk>\d+)/$",views.JoinIssue.as_view(),name="join"),
    url(r"leave/(?P<pk>\d+)/$",views.LeaveIssue.as_view(),name="leave"),   
    url(r"solve/(?P<pk>\d+)/$",views.SolveIssue,name="solve"),
    url(r"update/(?P<pk>\d+)/$",views.UpdateIssue,name="update"),  
    url(r'add_like/(?P<pk>\d+)/$', views.add_like, name='add_like'),
    url(r"accept/(?P<pk>\d+)/$", views.accept_answer, name="accept"),
    
    url(r"issues_list_api/$", views.issues_list_api, name="issues_list_api"),
    url(r"issue_detail_api/(?P<pk>\d+)/$", views.issue_detail_api, name="issue_detail_api"),
    url(r"answers_list_api/$", views.answers_list_api, name="answers_list_api"),
    

]

projects/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'projects'

urlpatterns = [
    url(r"^$", views.ListProjects, name="all"),
    url(r"^new/$", views.CreateProject.as_view(), name="create"),
    url(r"^issues/in/(?P<pk>\d+)/$",views.SingleProject.as_view(),name="single"),
    url(r"join/(?P<pk>\d+)/$",views.JoinProject.as_view(),name="join"),
    url(r"leave/(?P<pk>\d+)/$",views.LeaveProject.as_view(),name="leave"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteProject.as_view(),name="delete"),
    url(r"tagged/(?P<pk>\d+)/$",views.tagged,name="tagged"),
    url(r"complete/(?P<pk>\d+)/$",views.CompleteProject,name="complete"),
    url(r"joinper/(?P<pk>\d+)/$",views.CloseOrOpenJoin,name="joinper"),
    
    url(r"project_detail_api/(?P<pk>\d+)/$", views.project_detail_api, name="project_detail_api"),
    path('project_github_post/<str:pk>/<str:owner>/<str:repo>/',views.project_github_post, name="project_github_post"),
    url(r"projects_list_api/$", views.projects_list_api, name="projects_list_api"),
]

issues/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from projects.models import *
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
# Create your models here.

User=get_user_model()

class Issue(models.Model):

    name = models.CharField(max_length=255, unique=True)
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE,related_name='issues')
    created_at = models.DateTimeField(auto_now=True)
    message = RichTextField(blank=True,null=True)
    project = models.ForeignKey(Project,on_delete=models.SET_NULL,related_name="issues",null=True,blank=True)
    tags = TaggableManager()
    solve = models.BooleanField(default = False)
    members = models.ManyToManyField(User,through="IssueMember")
    deadline = models.DateField(auto_now_add=False,auto_now=False,default= None,null=True,blank=True)
    
    PRIORITY = [
        ('Critical','Critical'),
        ('major','major'),
        ('minor','minor'),
    ]
    priority = models.CharField(max_length=10,choices = PRIORITY,default='minor')
    

    def __str__(self):
        return '%s - %s' % (self.name,self.user.username)
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('issues:single',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['created_at']
        
        
class IssueMember(models.Model):
    issue = models.ForeignKey(Issue,null=True,on_delete=models.CASCADE, related_name="memberships",)
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE ,related_name='user_issues',)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("issue", "user")


class Answer(models.Model):
    issue = models.ForeignKey(Issue,null=True,related_name="answers",on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE ,related_name='answers',)
    message = RichTextField(blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User,related_name='likes_answers')
    accepted = models.BooleanField(default = False)
    
    def __str__(self):
        return '%s - %s' % (self.issue.name,str(self.user))

    class Meta:
        ordering = ['date_added']

issues/forms.py
from django import forms
from issues import models
from projects.models import Project
from django.db.models import Q
from taggit.forms import TagWidget

class IssueForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        exclude = ['user','created_at','members']
        model = models.Issue
        labels = {'solve':'mark as solved ?'}
        help_texts = {'tags':''}

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'message':forms.Textarea(attrs={'class':'form-control'}),
            'project':forms.Select(attrs={'class':'form-control'}),
            'tags':TagWidget(attrs={'class':'form-control','data-role':'tagsinput','placeholder':'press enter to add more tags'}),
            'solve':forms.CheckboxInput(attrs={}),
            'deadline':forms.DateInput(attrs={'class':'form-control','type':'date'}),
            'priority':forms.Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['project'].queryset = (
                models.Project.objects.filter( Q(user__pk=user.pk) | Q(members__pk=user.pk) )
            )




class AnswerForm(forms.ModelForm):
    class Meta:
        fields = ('message',)
        model=models.Answer
        labels = {'message':''}

issues/views.py
from django.http import  HttpResponse, Http404,HttpResponseRedirect
from braces.views import SelectRelatedMixin
from . import forms
from . import models
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse,reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404,render,redirect
from django.views import generic
from projects.models import Project,ProjectMember
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework import authentication, permissions
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import *


User = get_user_model()

class IssueList(SelectRelatedMixin, generic.ListView):
    model = models.Issue
    select_related = ("user", "project")


class CreateIssue(LoginRequiredMixin, SelectRelatedMixin,generic.CreateView):
    model = models.Issue
    form_class = forms.IssueForm
    template_name = 'issues/issue_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        form.save_m2m()
        return super().form_valid(form)
    

class DeleteIssue(LoginRequiredMixin, SelectRelatedMixin,generic.DeleteView):
    model = models.Issue
    select_related = ("user", "project")
    success_url = reverse_lazy("home")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Issue Deleted")
        return super().delete(*args, **kwargs)



class JoinIssue(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("issues:single",kwargs={"pk": self.kwargs.get("pk")})

    def get(self, request, *args, **kwargs):
        issue = get_object_or_404(models.Issue,pk=self.kwargs.get("pk"))

        try:
            models.IssueMember.objects.create(user=self.request.user,issue=issue)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(issue.message)))

        else:
            messages.success(self.request,"You are now a member of the {} issue.".format(issue.message))

        return super().get(request, *args, **kwargs)


class LeaveIssue(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("issues:single",kwargs={"pk": self.kwargs.get("pk")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.IssueMember.objects.filter(
                user=self.request.user,
                issue__pk=self.kwargs.get("pk")
            ).get()

        except models.IssueMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this issue because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this issue."
            )
        return super().get(request, *args, **kwargs)

@login_required
def SolveIssue(request,pk):

    issue = models.Issue.objects.get(id=pk)
    issue.solve = True
    issue.save()
    return redirect('home')

@login_required
def UpdateIssue(request,pk):

    issue = models.Issue.objects.get(id=pk)
    form = forms.IssueForm(instance=issue)
    message=''   
        
    if request.method == 'POST':
        form = forms.IssueForm(request.POST,instance=issue)
        if form.is_valid():
            form.save()
            message = "issue edited successfully"
            return redirect('/')
        else:
            message = "Error, please check the details again"
 
    context = {'form':form,'message':message,'issue':issue}
    return render(request, 'issues/issue_update_form.html', context)

@login_required
def IssueDetail(request,pk):
    issue = models.Issue.objects.get(pk=pk)
    answer = models.Answer(user=request.user,issue=issue)
    form = forms.AnswerForm(instance=answer)
    accepted_answers = issue.answers.filter(accepted = True)
    potential_answers = issue.answers.filter(accepted = False)
    message = ''

    if request.method == 'POST':
        form = forms.AnswerForm(request.POST,instance=answer)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            message = "Error, please check the details again"

    context = {'issue':issue,'form':form,'message':message,'accepted_answers':accepted_answers,'potential_answers':potential_answers}
    return render(request,'issues/issue_detail.html',context)

@login_required
def accept_answer(request,pk):

    answer = models.Answer.objects.get(pk=pk)
    issue = models.Issue.objects.get(pk=answer.issue.pk)
        
    if request.method == 'POST':
        answer.accepted = True
        answer.save()
        issue.solve = True
        issue.save()
        return HttpResponseRedirect(reverse('issues:single',args=[str(issue.pk)]))
    else:
        return render(request,'issues/answer_confirm.html',{'answer':answer,'issue':issue})


@login_required
def add_like(request,pk):
    answer = models.Answer.objects.get(id=pk)
    if answer.likes.filter(id=request.user.id).exists():
        answer.likes.remove(request.user)
    else:
        answer.likes.add(request.user)
    answer.save()

    return HttpResponse(answer.likes.count())



#API

@login_required
@api_view(['GET'])
def issues_list_api(request):
    issues = Issue.objects.all().order_by('id')
    serializer = IssueSerializer(issues, many=True)
    return Response(serializer.data)

@login_required
@api_view(['GET'])
def issue_detail_api(request,pk):
    issue = Issue.objects.get(pk=pk)
    serializer = IssueSerializer(issue)
    return Response(serializer.data)


@login_required
@api_view(['GET'])
def answers_list_api(request):
    answers = Answer.objects.all().order_by('id')
    serializer = AnswerSerializer(answers, many=True)
    return Response(serializer.data)

issues/templates/issues/_answer.html
<div class="media">
    <img src="{{answer.user.profile.profile_pic}}" width="36" height="36" class="rounded-circle mr-2"
        alt="profile_pic">
    <div class="media-body">
        <small class="float-right text-navy">{{answer.date_added}}</small>
        <strong><a href="{% url 'accounts:profile' pk=answer.user.pk %}">{{answer.user.username}}</a></strong> Answered in <strong><a href="{% url 'issues:single' pk=answer.issue.pk %}">{{answer.issue.name}}</a></strong>
        <br />

        <div style="font-size:15px;" class="border text-sm text-muted p-2 mt-1">
            {{answer.message|safe}}
        </div>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style>
            .btn-secondary {
                background: #ed2553;
                border-radius: 3px;
                box-shadow: 0 10px 20px -8px rgb(240, 75, 113);
                padding: 5px 9px;
                font-size: 18px;
                border: none;
                outline: none;
                color: #ffffff;
                text-decoration: none;
                -webkit-transition: 0.3s ease;
                transition: 0.3s ease;
            }

            .fa-thumbs-down {
                margin-right: 10px;
            }

            .fa-thumbs-up {
                margin-right: 10px;
            }
        </style>
        
        {% if user in answer.likes.all %}
        <button onclick="myFunction(this)" class="btn-secondary likes-button" type="button"
            data-ansid="{{answer.pk}}"><i class="fa fa-thumbs-down"></i><strong
                id="like_count_{{answer.pk}}">{{ answer.likes.count }}</strong>
        </button>
        {% else %}
        <button onclick="myFunction(this)" class="btn-secondary likes-button" type="button"
            data-ansid="{{answer.pk}}"><i class="fa fa-thumbs-up"></i><strong
                id="like_count_{{answer.pk}}">{{ answer.likes.count }}</strong>
        </button>
        {% endif %}
        
        {% if issue.user == user and issue.solve == False and answer.accepted == False %}
        <a href="{% url 'issues:accept' pk=answer.pk %}" class="btn btn-success">accept
            answer</a>
        {% endif %}
    </div>
</div>
<hr />

issues/templates/issues/_issue.html
<tr>
	<td><a href="{% url 'issues:single' pk=issue.pk %}">{{issue.name}}</a>
	</td>
	<td class="d-none d-xl-table-cell">{{issue.created_at|date:"d/m/yy"}}</td>
	<td class="d-none d-xl-table-cell">{{issue.user.username}}</td>
	<td class="d-none d-xl-table-cell">{{issue.project.name}}</td>
	<td class="d-none d-xl-table-cell">{{issue.members.count}}</td>
	<td class="d-none d-xl-table-cell">{{issue.priority}}</td>
	<td class="d-none d-xl-table-cell">{{issue.deadline|date:"d/m/yy"}}</td>

	{% if issue.solve == False %}
	{% if issue.user == user and not hide_delete %}
	<td><span class="badge badge-danger"><a style="color:white;" href="{% url 'issues:solve' pk=issue.pk %}">Mark
				solved</a></span></td>
	{% else %}
	<td><span class="badge badge-warning">Pending</span></td>
	{% endif %}

	{% else %}
	<td><span class="badge badge-success">Done</span></td>

	{% endif %}

	{% if issue.user == user and not hide_delete %}
	<td class="table-action">
		<a href="{% url 'issues:update' pk=issue.pk %}"><i class="align-middle" data-feather="edit-2"></i></a>
		<a href="{% url 'issues:delete' pk=issue.pk %}"><i class="align-middle" data-feather="trash"></i></a>
	</td>
	{% else %}

	{% if issue.solve == False %}

	{% if user in issue.members.all %}
	<td><span class="badge badge-danger"><a style="color:white;"
				href="{% url 'issues:leave' pk=issue.pk %}">quit</a></span></td>
	{% else %}
	<td><span class="badge badge-success"><a style="color:white;"
				href="{% url 'issues:join' pk=issue.pk  %}">workon</a></span></td>
	{% endif %}

	{% else %}

	{% if user in issue.members.all %}
	<td><span class="badge badge-danger"><a style="color:white;"
				href="{% url 'issues:leave' pk=issue.pk %}">quit</a></span></td>
	{% endif %}

	{% endif %}

	{% endif %}
</tr>

issues/templates/issues/answer_confirm.html
{% extends "issues/issue_base.html" %}
{% block issue_content %}

<main class="content">
    <div class="container-fluid p-0">

        <div class="row mb-2 mb-xl-3">
            <div class="col-auto d-none d-sm-block">
                <h3><strong>Are you sure you want to accept this answer</strong><br> and mark this issue ?</h3>
            </div>
        </div>
        <div class="media">
            <img src="{{answer.user.profile.profile_pic}}" width="36" height="36" class="rounded-circle mr-2"
                alt="profile_pic">
            <div class="media-body">
                <small class="float-right text-navy">{{answer.date_added}}</small>
                <strong>{{answer.user.username}}</strong> Answered <br />

                <div style="font-size:15px;" class="border text-sm text-muted p-2 mt-1">
                    {{answer.message|safe}}
                </div>

            </div>
        </div>
        <hr />

    </div>


    <form method="POST" action="{% url 'issues:accept' pk=answer.pk %}">
        {% csrf_token %}
        <input class="btn btn-pill btn-success" type="submit" value="Confirm">
        <a class="btn btn-pill btn-primary"
            href="{% url 'issues:single' pk=issue.pk %}">Cancel</a>
    </form>

</main>
{% endblock %}

issues/templates/issues/issue_base.html
{% extends "base.html" %}

{% block content %}
{% block preissue%}{% endblock %}
{% block issue_content %}{% endblock %}
{% block issue_issue%}{% endblock %}

{% endblock %}

issues/templates/issues/issue_confirm_delete.html
{% extends "issues/issue_base.html" %}
{% block issue_content %}

<main class="content">
	<div class="container-fluid p-0">

		<div class="row mb-2 mb-xl-3">
			<div class="col-auto d-none d-sm-block">
				<h3><strong>Are you sure you want to delete this issue ?</strong><br> Once deleted there is no going
					back</h3>
			</div>
		</div>



		<div class="row">
			<div class="col-12 col-lg-8 col-xxl-9 d-flex">
				<div class="card flex-fill">
					<div class="card-header">

						<h5 class="card-title mb-0">Issues</h5>
					</div>
					<table class="table table-hover my-0">
						<thead>
							<tr>
								<th>Name</th>
								<th class="d-none d-xl-table-cell">Created At</th>
								<th class="d-none d-xl-table-cell">Created By</th>
								<th class="d-none d-xl-table-cell">Project</th>
								<th class="d-none d-xl-table-cell">Members Working</th>
								<th class="d-none d-xl-table-cell">Priority</th>
								<th class="d-none d-xl-table-cell">Deadline</th>
								<th>Status</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{% include 'issues/_issue.html' with issue=object hide_delete=True %}
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
	<form method="POST">
		{% csrf_token %}
		<input class="btn btn-pill btn-danger" type="submit" value="Confirm Delete">
		<a class="btn btn-pill btn-primary"
			href="{% url 'issues:single' pk=issue.pk %}">Cancel</a>
	</form>

</main>
{% endblock %}

issues/templates/issues/issue_detail.html
{% extends "issues/issue_base.html" %}
{% load static %}
{% block issue_content %}
<div>
    <main class="content">
        <div class="container-fluid p-0">

            <h1 class="h3 mb-3">Issue</h1>

            <div class="row">
                <div class="col-md-4 col-xl-3">
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Issue Details</h5>
                        </div>
                        <div class="card-body text-center">
                            <h1 style="font-size: 35px;" class="card-title mb-0">{{issue.name.capitalize}}</h1>
                            <div class="text-muted mb-2">{{issue.project.name.capitalize}}</div>

                            <div>

                                {% if issue.solve == False %}
                                {% if issue.user == user and not hide_delete %}
                                <span class="badge badge-danger"><a style="color:white;"
                                        href="{% url 'issues:solve' pk=issue.pk %}">Mark
                                        solved</a></span>
                                {% else %}
                                <span class="badge badge-warning">Pending</span>
                                {% endif %}
                                {% else %}
                                <span class="badge badge-success">Done</span>

                                {% endif %}

                                {% if issue.solve == False %}
                                {% if issue.user == user %}
                                <a href="{% url 'issues:update' pk=issue.pk %}"><i class="align-middle"
                                        data-feather="edit-2"></i></a>
                                <a href="{% url 'issues:delete' pk=issue.pk %}"><i class="align-middle"
                                        data-feather="trash"></i></a>
                                {% else %}
                                {% if user in issue.members.all %}
                                <td><span class="badge badge-danger"><a style="color:white;"
                                            href="{% url 'issues:leave' pk=issue.pk %}">quit</a></span></td>
                                {% else %}
                                <td><span class="badge badge-success"><a style="color:white;"
                                            href="{% url 'issues:join' pk=issue.pk  %}">workon</a></span></td>
                                {% endif %}
                                {% endif %}
                                {% else %}

                                {% if user in issue.members.all and issue.user != user %}
                                <td><a href="{% url 'issues:leave' pk=issue.pk %}"></span>quit</a></td>
                                {% endif %}
                                {% endif %}
                                {% if user in issue.members.all or user == issue.user %}
                                <br><br>
                                <a class="btn btn-primary btn-sm" href="{% url 'chats:all' %}"><span
                                        data-feather="message-square"></span>Discuss</a>
                                {% endif %}

                            </div>
                        </div>
                        <hr class="my-0" />
                        <div class="card-body">
                            <h5 class="h6 card-title">Tags</h5>
                            {% for tag in issue.tags.all %}
                            <a href="{% url 'projects:tagged' pk=tag.pk %}"
                                class="badge badge-primary mr-1 my-1">{{tag|safe}}</a>
                            {% endfor %}

                        </div>
                        <hr class="my-0" />
                        <div class="card-body">
                            <h5 class="h6 card-title">About</h5>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-1"><span data-feather="file-plus" class="feather-sm mr-1"></span> Created
                                    At <strong>{{issue.created_at}}</strong></li>
                                <li class="mb-1"><span data-feather="user" class="feather-sm mr-1"></span> Created By <a
                                        href="{% url 'accounts:profile' pk=issue.user.pk %}">
                                        {{issue.user.username}}</a></li>
                                <li class="mb-1"><span data-feather="users" class="feather-sm mr-1"></span> People
                                    working on this <strong>{{issue.members.count}}</strong></li>
                                {% if issue.project %}
                                <li class="mb-1"><span data-feather="book" class="feather-sm mr-1"></span> Project <a
                                        href="{% url 'projects:single' pk=issue.project.pk %}">
                                        {{issue.project.name}}</a></li>
                                {% endif %}
                                <li class="mb-1"><span data-feather="list" class="feather-sm mr-1"></span> Priority
                                    <strong> {{issue.priority}}</strong></li>
                                <li class="mb-1"><span data-feather="alert-circle" class="feather-sm mr-1"></span>
                                    Deadline <strong> {{issue.deadline}}</strong></li>


                            </ul>
                        </div>
                        <hr class="my-0" />
                    </div>
                </div>

                <div class="col-md-8 col-xl-9">
                    <div class="card">
                        <div class="card-header">

                            <h5 class="card-title mb-0">Message</h5>
                        </div>
                        <div class="card-body h-100">
                            <hr />
                            <div>
                                {{issue.message|safe}}

                            </div>
                            <hr />
                            {% if not issue.answers.all %}
                            <div>
                                <h1>No Answers yet</h1>
                            </div>
                            <hr />
                            {% else %}

                            {% if accepted_answers %}
                            <h3>Accepted Answers</h3><br>
                            {% for answer in accepted_answers %}
                            {% include 'issues/_answer.html' %}
                            {% endfor %}
                            {% endif %}

                            {% if potential_answers %}
                            <h3>Potential Answers</h3><br>
                            {% for answer in potential_answers %}
                            {% include 'issues/_answer.html' %}
                            {% endfor %}
                            {% endif %}
                            {% endif %}

                            {% if user in issue.members.all or issue.user == user %}

                            <div>
                                <h2><br>Your Answer</h2>
                            </div>
                            <form method="POST" action="{% url 'issues:single' pk=issue.pk %}">
                                {% csrf_token %}
                                {{form.media}}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary">Post</button>

                            </form>
                            {% else %}
                            <div>
                                <h2><br>Join the issue to post an answer</h2>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>
</div>


{% endblock %}
{% block script %}
<script type="text/javascript" src="{% static 'js/like.js' %}"></script>
{% endblock %}

issues/templates/issues/issue_form.html
{% extends "issues/issue_base.html" %}
{% block issue_content %}

<main class="content">
	<div class="container-fluid p-0">
		<div class="row">
			<div class="card">
				<div class="card-header">
					<h5 class="card-title"><strong>Raise</strong> new Issue</h5>
				</div>
				<div class="card-body">

					<form method="POST" action="{% url 'issues:create' %}">
						{% csrf_token %}
						{{form.media}}
						{{form.as_p}}
						<div class="form-group row">
							<div class="col-sm-10 ml-sm-auto">
								<button type="submit" class="btn btn-primary">Create</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</main>

{% endblock %}

issues/templates/issues/issue_update_form.html
{% extends "issues/issue_base.html" %}
{% block issue_content %}

<main class="content">
	<div class="container-fluid p-0">
		<div class="row">
			<div class="card">
				<div class="card-header">
					<h5 class="card-title"><strong>Raise</strong> new Issue</h5>
				</div>
				<div class="card-body">

					<form method="POST" action="{% url 'issues:update' pk=issue.pk %}">
						{% csrf_token %}
						{{form.media}}
						{{form.as_p}}
						<div class="form-group row">
							<div class="col-sm-10 ml-sm-auto">
								<button type="submit" class="btn btn-primary">Edit</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</main>

{% endblock %}