accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"^register/$",views.register,name='register'),
    url(r"^login/$",views.loginUser,name='login'),
    url(r"^logout/$",views.logoutUser,name='logout'),
    url(r"^profile/(?P<pk>\d+)/$",views.profile_page,name='profile'),
    url(r"^deluser/$",views.delete_user,name="deluser"),

    url(r"^profile_api/(?P<pk>\d+)/$",views.profile_api,name='profile_api')
]

bugtracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('search',views.search,name='search'),
    path('set',views.set,name="set"),
    path('changepass',views.changepass,name="changepass"),
    url(r"^accounts/",include('accounts.urls',namespace="accounts")),
    url(r"^projects/", include("projects.urls", namespace="projects")),
    url(r"^issues/",include("issues.urls", namespace="issues")),
    url(r"^chats/",include("chats.urls", namespace="chats")),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,include

app_name='Chats'

urlpatterns = [
	path('all/', views.all, name="all"),	
]

projects/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'projects'

urlpatterns = [
    url(r"^$", views.ListProjects, name="all"),
    url(r"^new/$", views.CreateProject.as_view(), name="create"),
    url(r"^issues/in/(?P<pk>\d+)/$",views.SingleProject.as_view(),name="single"),
    url(r"join/(?P<pk>\d+)/$",views.JoinProject.as_view(),name="join"),
    url(r"leave/(?P<pk>\d+)/$",views.LeaveProject.as_view(),name="leave"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteProject.as_view(),name="delete"),
    url(r"tagged/(?P<pk>\d+)/$",views.tagged,name="tagged"),
    url(r"complete/(?P<pk>\d+)/$",views.CompleteProject,name="complete"),
    url(r"joinper/(?P<pk>\d+)/$",views.CloseOrOpenJoin,name="joinper"),
    
    url(r"project_detail_api/(?P<pk>\d+)/$", views.project_detail_api, name="project_detail_api"),
    path('project_github_post/<str:pk>/<str:owner>/<str:repo>/',views.project_github_post, name="project_github_post"),
    url(r"projects_list_api/$", views.projects_list_api, name="projects_list_api"),
]

projects/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.contrib.auth import get_user_model
from django import template
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

User = get_user_model()
register = template.Library()

class Project(models.Model):
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE,related_name='projects')
    name = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now=True)
    description = RichTextField(blank=True,null=True)
    tags = TaggableManager()
    complete = models.BooleanField(default = False)
    members = models.ManyToManyField(User,through="ProjectMember")
    projectJoinPermission = models.BooleanField(default=True)
    repoowner = models.CharField(max_length=255,blank=True,null=True)
    githubrepo = models.CharField(max_length=255,blank=True,null=True)

    def __str__(self):
        return '%s - %s' % (self.name,self.user.username)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("projects:single", kwargs={"pk": self.pk})


    class Meta:
        ordering = ["name"]
        unique_together = ['user','name']

class ProjectMember(models.Model):
    project = models.ForeignKey(Project,null=True,on_delete=models.CASCADE, related_name="memberships",)
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE ,related_name='user_projects',)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("project", "user")

projects/forms.py
from django import forms
from projects import models
from taggit.forms import TagWidget

class ProjectForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        exclude = ['user','created_at','members','complete','repoowner','githubrepo']
        model = models.Project
        help_texts = {'tags':''}

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'tags':TagWidget(attrs={'class':'form-control','data-role':'tagsinput','placeholder':'press enter to add more tags'}),
        } 

projects/views.py
from django.contrib import messages
from braces.views import SelectRelatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse,reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404,redirect,render
from django.views import generic
from projects.models import Project,ProjectMember
from issues.models import *
from . import models
from . import forms
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework import authentication, permissions
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import *

# Create your views here.

class CreateProject(LoginRequiredMixin, SelectRelatedMixin,generic.CreateView):
    
    model = Project
    form_class = forms.ProjectForm
    template_name = 'projects/project_form.html'
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        form.save_m2m()
        return super().form_valid(form)

@login_required
def tagged(request,pk):
    tag=get_object_or_404(Tag,pk=pk)
    issues=Issue.objects.filter(tags=tag)
    projects=Project.objects.filter(tags=tag)
    search_term = str(tag)
    context = {'search_term':search_term,'tag':tag,'projects':projects,'issues':issues}
    return render(request,'search_result.html',context) 

class SingleProject(generic.DetailView):
    model = Project


@login_required
def ListProjects(request):
    projects = Project.objects.all()
    context = {'projects':projects}
    return render(request,'projects/project_list.html',context)


class JoinProject(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"pk": self.kwargs.get("pk")})

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project,pk=self.kwargs.get("pk"))

        try:
            ProjectMember.objects.create(user=self.request.user,project=project)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(project.name)))

        else:
            messages.success(self.request,"You are now a member of the {} project.".format(project.name))

        return super().get(request, *args, **kwargs)


class LeaveProject(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"pk": self.kwargs.get("pk")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.ProjectMember.objects.filter(
                user=self.request.user,
                project__pk=self.kwargs.get("pk")
            ).get()

        except models.ProjectMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this project because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this project."
            )
        return super().get(request, *args, **kwargs)



class DeleteProject(LoginRequiredMixin, SelectRelatedMixin,generic.DeleteView):
    model = models.Project
    select_related = ("user",)
    success_url = reverse_lazy("projects:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Project Deleted")
        return super().delete(*args, **kwargs)

def CompleteProject(request,pk):

    project = models.Project.objects.get(id=pk)
    project.complete = True
    project.save()
    return redirect('projects:all')


#API

@login_required
@api_view(['GET'])
def projects_list_api(request):
    projects = models.Project.objects.all().order_by('id')
    serializer = ProjectSerializer(projects, many=True)
    return Response(serializer.data)

@login_required
@api_view(['GET'])
def project_detail_api(request,pk):
    project = Project.objects.get(pk=pk)
    serializer = ProjectSerializer(project)
    return Response(serializer.data)

@login_required
@api_view(['GET','POST'])
def project_github_post(request,pk,owner,repo):
    project = Project.objects.get(pk=pk)
    project.repoowner = owner
    project.githubrepo = repo
    project.save()
    serializer = ProjectRepoSerializer(project)
    return Response(serializer.data)


def CloseOrOpenJoin(request,pk):
    project = models.Project.objects.get(id=pk)
    if project.projectJoinPermission == True:
        project.projectJoinPermission = False
    else:
        project.projectJoinPermission = True
    project.save()
    return redirect('projects:single',pk)

projects/templates/projects/_project.html
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h2 style="font-size: large;" class="card-title"><strong>{{project.name.capitalize}}</strong></h2>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-5 col-md-4">
                    <div class="nav flex-column nav-pills nav-secondary" id="v-pills-{{project.pk}}tab" role="tablist"
                        aria-orientation="vertical">
                        <a class="nav-link active" id="v-pills-{{project.pk}}home-tab" data-toggle="pill"
                            href="#v-pills-{{project.pk}}home" role="tab" aria-controls="v-pills-{{project.pk}}home"
                            aria-selected="true">Home</a>
                        <a class="nav-link" id="v-pills-{{project.pk}}tags-tab" data-toggle="pill"
                            href="#v-pills-{{project.pk}}tags" role="tab" aria-controls="v-pills-{{project.pk}}tags"
                            aria-selected="false">tags</a>
                        <a class="nav-link" href="{% url 'projects:single' pk=project.pk %}">view</a>
                    </div>
                </div>
                <div class="col-7 col-md-8">
                    <div class="tab-content" id="v-pills-{{project.pk}}tabContent">
                        <div class="tab-pane fade show active" id="v-pills-{{project.pk}}home" role="tabpanel"
                            aria-labelledby="v-pills-{{project.pk}}home-tab">
                            <h5 class="card-title mb-4">{{ project.members.count }}
                                member{{ project.members.count|pluralize }}</h5>
                            {% if project.complete == False %}
                            <span class="text-danger"> <i
                                    class="mdi mdi-arrow-bottom-right"></i>{{ project.issues.count }}
                                issue{{ project.issues.count|pluralize }}</span><br>
                            {% else %}
                            <span class="text-success"> <i
                                    class="mdi mdi-arrow-bottom-right"></i>{{ project.issues.count }}
                                issue{{ project.issues.count|pluralize }}</span>
                            {% endif %}
                            <p>{{project.description|safe}}</p>
                        </div>
                        <div class="tab-pane fade" id="v-pills-{{project.pk}}tags" role="tabpanel"
                            aria-labelledby="v-pills-{{project.pk}}tags-tab">
                            <br><br>
                            {% for tag in project.tags.all %}
                            <a href="{% url 'projects:tagged' pk=tag.pk %}"
								class="badge badge-primary mr-1 my-1">{{tag|safe}}</a>
							{% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

projects/templates/projects/project_base.html
{% extends "base.html" %}
{% block content %}

{% block project_content %}{% endblock %}
{% block issueproject %}{% endblock %}

{% endblock %}

projects/templates/projects/project_confirm_delete.html
{% extends "projects/project_base.html" %}
{% block project_content %}


<main class="content">
	<div class="container-fluid p-0">

		<div class="row mb-2 mb-xl-3">
			<div class="col-auto d-none d-sm-block">
				<h3><strong>Are you sure you want to delete this project ?</strong><br> Once deleted there is no going
					back</h3>
				{% if project.issues.count > 0 %}
				<h3>The project still contains some issues , which will not be deleted </h3>
				{% endif %}

			</div>
		</div>


		<div class="w-100">
			<div class="row">

				{% include "projects/_project.html" with project=object hide_delete=True %}
			</div>
		</div>
	</div>
	<form style="margin-left:12px" method="POST">
		{% csrf_token %}
		<input class="btn btn-pill btn-danger" type="submit" value="Confirm Delete">
		<a class="btn btn-pill btn-primary" href="{% url 'projects:single' pk=object.pk %}">Cancel</a>
	</form>
</main>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends "projects/project_base.html" %}
{% block project_content %}
{% load static %}

<div>
	<main class="content">
		<div class="container-fluid p-0">

			<h1 class="h3 mb-3">Project</h1>

			<div class="row">
				<div class="col-md-4 col-xl-3">
					<div class="card mb-3">
						<div class="card-header">
							<h5 class="card-title mb-0">Project Details</h5>
						</div>
						<div class="card-body text-center">
							<h1 style="font-size: 25px;" class="card-title mb-0">{{project.name.capitalize}}</h1>
							<div class="text-muted mb-2">{{project.user.username}}</div>

							<div>

								{% if project.complete == False %}
								{% if project.user == user %}
								<span class="badge badge-danger"><a style="color:white;"
										href="{% url 'projects:complete' pk=project.pk %}">Mark
										Completed</a></span>
								<span class="badge badge-warning"><a style="color:white;"
										href="{% url 'projects:delete' pk=project.pk %}">
										Delete</a></span>
								{% if project.projectJoinPermission == True %}
								<span class="badge badge-success"><a style="color:white;"
										href="{% url 'projects:joinper' pk=project.pk %}">
										Open to all</a></span>
								{% else %}
								<span class="badge badge-primary"><a style="color:white;"
										href="{% url 'projects:joinper' pk=project.pk %}">
										Joined Only</a></span>
								{% endif %}

								{% else %}
								<span class="badge badge-warning">Pending</span>
								{% endif %}
								{% else %}
								<span class="badge badge-success">Done</span>

								{% endif %}

								{% if project.complete == False and project.user != user %}

								{% if user in project.members.all %}
								<span class="badge badge-danger"><a style="color:white;"
										href="{% url 'projects:leave' pk=project.pk %}">Leave</a></span>
								{% else %}
								{% if project.projectJoinPermission == True %}
								<span class="badge badge-success"><a style="color:white;"
										href="{% url 'projects:join' pk=project.pk  %}">Join</a></span>
								{% else %}
								<span class="badge badge-secondary">Members only</span>
								{% endif %}
								{% endif %}

								{% else %}

								{% if user in project.members.all and user != project.user %}
								<td><span class="badge badge-danger"><a style="color:white;"
											href="{% url 'projects:leave' pk=project.pk %}">leave</a></span></td>
								{% endif %}
								{% endif %}

								{% if user in project.members.all or user == project.user %}
								<br><br>
								<a class="btn btn-primary btn-sm" href="{% url 'chats:all' %}"><span
										data-feather="message-square"></span>Discuss</a>
								{% endif %}

							</div>
						</div>
						<hr class="my-0" />
						<div class="card-body">
							<h5 class="h6 card-title">Tags</h5>
							{% for tag in project.tags.all %}
							<a href="{% url 'projects:tagged' pk=tag.pk %}"
								class="badge badge-primary mr-1 my-1">{{tag|safe}}</a>
							{% endfor %}

						</div>
						<hr class="my-0" />
						<div class="card-body">
							<h5 class="h6 card-title">About</h5>
							<ul class="list-unstyled mb-0">
								<li class="mb-1"><span data-feather="file-plus" class="feather-sm mr-1"></span> Created
									At
									<strong> {{project.created_at}}</strong></li>
								<li class="mb-1"><span data-feather="user" class="feather-sm mr-1"></span> Created By <a
										href="{% url 'accounts:profile' pk=project.user.pk %}">
										{{project.user.username}}</a></li>

								<li class="mb-1"><span data-feather="users" class="feather-sm mr-1"></span> Project
									Members <strong> {{project.members.count}}</strong></li>
								<li class="mb-1"><span data-feather="alert-triangle" class="feather-sm mr-1"></span>
									Total issues <strong> {{project.issues.count}}</strong></li>
							</ul>
						</div>
						<hr class="my-0" />
					</div>
				</div>

				<style>
					.hide {
						display: none;
					}
				</style>

				<div class="col-md-8 col-xl-9">
					<div class="card">
						<div class="card-header">
							<h5 class="card-title mb-0">Description</h5>
						</div>

						<div class="card-body h-100">

							{% if user == project.user %}
							<button type="button" class="btn btn-success" data-toggle="modal"
								data-target="#defaultModalSuccess">
								Edit Project Code
							</button>
							<br><br>
							<div class="modal fade" id="defaultModalSuccess" tabindex="-1" role="dialog"
								aria-hidden="true">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">Github Repository for the Project</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div id="popupwindowid" class="modal-body m-3">
											<div class="form-group">
												<label class="form-label">Repository Owner</label>
												<input onkeyup="CheckRepo()" id="repoowner" type="name"
													class="form-control" placeholder="Owner">
											</div>
											<div class="form-group">
												<label class="form-label">Repository Name</label>
												<input onkeyup="CheckRepo()" id="reponame" type="name"
													class="form-control" placeholder="Repo name">
											</div>
											<div id="PopupWindowAlert" class="alert alert-danger alert-dismissible hide"
												role="alert">
												<button type="button" class="close" data-dismiss="alert"
													aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
												<div id="PopupWindowAlertMessage" class="alert-message">
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary"
												data-dismiss="modal">Close</button>
											<button id="PopupWindowButton" onclick="SaveRepo()" type="button"
												class="btn btn-danger">Save
												changes</button>
										</div>
									</div>
								</div>
							</div>
							{% endif %}

							{% if project.githubrepo == None or project.repoowner == None %}
							{% else %}
							{% if user in project.members.all or project.user == user %}
							<div class="alert alert-success alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<div class="alert-message">
									<h4 class="alert-heading">Github Repository</h4><a id="githubbutton" href="#"
										target="_blank"><button class="btn mb-1 btn-github"><i
												class="align-middle fab fa-github"></i>
											Github</button></a><br>
									<br>
									<nav aria-label="breadcrumb">
										<ol id="path-wrapper" class="breadcrumb">
										</ol>
									</nav>
									<div id="list-wrapper" class="dropdown-menu mb-2"
										style="position:static;display:block;">
									</div>
									<iframe id="sandboxframe" class="hide" src=""
										style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"></iframe>
								</div>
							</div>
							{% endif %}
							{% endif %}
							<hr />
							<div>
								{{project.description|safe}}
							</div>
							<hr />
							{% if user in project.members.all or project.user == user %}
							{% if not project.issues.all %}
							<div>
								<h3>No Issues yet</h3>
							</div>
							<hr />
							{% else %}

							<table class="table table-hover my-0">
								<thead>
									<tr>
										<th>Name</th>
										<th class="d-none d-xl-table-cell">Created At</th>
										<th class="d-none d-xl-table-cell">Created By</th>
										<th class="d-none d-xl-table-cell">Project</th>
										<th class="d-none d-xl-table-cell">Members Working</th>
										<th class="d-none d-xl-table-cell">Priority</th>
										<th class="d-none d-xl-table-cell">Deadline</th>
										<th>Status</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for issue in project.issues.all %}
									{% include "issues/_issue.html" %}
									{% endfor %}

								</tbody>
							</table>
							{% endif %}
						</div>
					</div>
				</div>

				{% else %}
				<div class="card-header">
					<h2 style="font-size: 25px;" class="card-title mb-0">You are not a member of this
						project, Join to view the Issues</h2>
				</div>

				{% endif %}
			</div>
		</div>
	</main>
</div>
{% endblock %}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/API.js' %}"></script>
<script type="text/javascript">

	const owner = "{{project.repoowner}}";
	const repo = "{{project.githubrepo}}";
	var listwrapper = document.getElementById('list-wrapper');
	var pathwrapper = document.getElementById('path-wrapper');
	const githubbutton = document.getElementById('githubbutton');
	githubbutton.href = `https://github.com/${owner}/${repo}`;

	buildList(`https://api.github.com/repos/${owner}/${repo}/git/trees/master?`, `${repo}`);

	function buildList(url, path) {
		fetch(url)
			.then((resp) => resp.json())
			.then(function (data) {
				listwrapper.innerHTML = "";
				if (data.content != undefined)
					pathwrapper.innerHTML += `<li class="breadcrumb-item"><a>${path}</a></li>`;
				else
					pathwrapper.innerHTML +=
					`<li onClick='buildPath("${url}","${path}")' class="breadcrumb-item"><a href="#">${path}</a></li>`;

				for (index in data.tree) {
					item =
						`<a onClick='buildList("${data.tree[index].url}","${data.tree[index].path}")' class="dropdown-item">${data.tree[index].path}</a>`
					listwrapper.innerHTML += item;
				}
				if (data.content != undefined) {

					var fullpath = "",
						i;
					for (i = 1; i < pathwrapper.childElementCount - 1; i++)
						fullpath += '/' + pathwrapper.children[i].children[0].innerHTML;

					fullpath += '/' + pathwrapper.children[i].children[0].innerHTML;

					console.log(fullpath);
					listwrapper.innerHTML = `<a class="dropdown-item">${path}</a>`
					sandboxframe.classList.remove('hide');
					sandboxframe.src =
						`https://codesandbox.io/embed/github/${owner}/${repo}/tree/master/?hidedevtools=1&codemirror=1&hidedevtools=1&hidenavigation=1&view=editor&expanddevtools=2&module=${fullpath}&theme=dark"`
					console.log(sandboxframe.src);
				}
			})
	}

	function buildPath(url, path) {

		var i, j = pathwrapper.childElementCount;
		for (i = 0; i < pathwrapper.childElementCount; i++) {
			if (pathwrapper.children[i].children[0].innerHTML == path) {
				while (i < pathwrapper.childElementCount)
					pathwrapper.removeChild(pathwrapper.lastChild);
			}
		}
		buildList(url, path);
	}
</script>

<script type="text/javascript">
	const repoowner = document.getElementById('repoowner');
	const reponame = document.getElementById('reponame');
	const popupwindow = document.getElementById('popupwindowid');
	const PopupWindowAlertMessage = document.getElementById('PopupWindowAlertMessage');
	const PopupWindowAlert = document.getElementById('PopupWindowAlert');
	const PopupWindowButton = document.getElementById('PopupWindowButton');

	function CheckRepo() {
		PopupWindowAlert.classList.remove('hide');
		url = `https://api.github.com/repos/${repoowner.value}/${reponame.value}`
		fetch(url)
			.then((resp) => resp.json())
			.then(function (data) {
				if (data.message != undefined) {
					dangeralert();
					PopupWindowAlertMessage.innerHTML = `Repo ${data.message}`;
					dangerbutton();
				} else {
					successalert();
					PopupWindowAlertMessage.innerHTML = "Repo found";
					successbutton();
				}
			});
	}

	function SaveRepo() {
		console.log(API);
		if (PopupWindowButton.classList.contains('btn-success') && PopupWindowAlert.classList.contains('alert-success')) {
			var url =
				`${API}/projects/project_github_post/{{project.pk}}/${repoowner.value}/${reponame.value}`
			fetch(url,{
			mode:"no-cors"
		}).then(function (response) {
				window.open(`https://githubbox.com/${repoowner.value}/${reponame.value}`, "_blank")
				window.location.reload();
				buildList(`https://api.github.com/repos/${repoowner.value}/${reponame.value}/git/trees/master?`,
					`${reponame.value}`);
			})
		}
	}

	function dangeralert() {
		if (PopupWindowAlert.classList.contains('alert-success')) {
			PopupWindowAlert.classList.remove('alert-success');
			PopupWindowAlert.classList.add('alert-danger');
		}
	}

	function successalert() {
		if (PopupWindowAlert.classList.contains('alert-danger')) {
			PopupWindowAlert.classList.remove('alert-danger');
			PopupWindowAlert.classList.add('alert-success');
		}
	}

	function dangerbutton() {
		if (PopupWindowButton.classList.contains('btn-success')) {
			PopupWindowButton.classList.remove('btn-success');
			PopupWindowButton.classList.add('btn-danger');
		}
	}

	function successbutton() {
		if (PopupWindowButton.classList.contains('btn-danger')) {
			PopupWindowButton.classList.remove('btn-danger');
			PopupWindowButton.classList.add('btn-success');
		}
	}
</script>
{% endblock %}

projects/templates/projects/project_form.html
{% extends "projects/project_base.html" %}
{% block project_content %}

<main class="content">
	<div class="container-fluid p-0">
		<div class="row">
			<div class="card">
				<div class="card-header">
					<h5 class="card-title"><strong>Create</strong> a new Project</h5>
				</div>
				<div class="card-body">

					<form method="POST" action="{% url 'projects:create' %}">
						{% csrf_token %}
						{{form.media}}
						{{form.as_p}}
						<div class="form-group row">
							<div class="col-sm-10 ml-sm-auto">
								<button type="submit" class="btn btn-primary">Create</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</main>

{% endblock %}

projects/templates/projects/project_list.html
{% extends "projects/project_base.html" %}
{% block project_content %}

<main class="content">
    <div class="container-fluid p-0">

        <div class="row mb-2 mb-xl-3">
            <div class="col-auto d-none d-sm-block">
                <h3><strong>Projects</strong> List</h3>
            </div>
        </div>

        <div class="w-100">
            <div class="row">

                {% for project in projects %}
                {% include "projects/_project.html" %}
                {% endfor %}

            </div>
        </div>
    </div>
</main>
{% endblock %}