accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"^register/$",views.register,name='register'),
    url(r"^login/$",views.loginUser,name='login'),
    url(r"^logout/$",views.logoutUser,name='logout'),
    url(r"^profile/(?P<pk>\d+)/$",views.profile_page,name='profile'),
    url(r"^deluser/$",views.delete_user,name="deluser"),

    url(r"^profile_api/(?P<pk>\d+)/$",views.profile_api,name='profile_api')
]

bugtracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('search',views.search,name='search'),
    path('set',views.set,name="set"),
    path('changepass',views.changepass,name="changepass"),
    url(r"^accounts/",include('accounts.urls',namespace="accounts")),
    url(r"^projects/", include("projects.urls", namespace="projects")),
    url(r"^issues/",include("issues.urls", namespace="issues")),
    url(r"^chats/",include("chats.urls", namespace="chats")),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,include

app_name='Chats'

urlpatterns = [
	path('all/', views.all, name="all"),	
]

issues/urls.py
from django.conf.urls import url
from . import views

app_name='Issues'

urlpatterns = [
    url(r"^$", views.IssueList.as_view(), name="all"),
    url(r"new/$", views.CreateIssue.as_view(), name="create"),
    url(r"by/(?P<pk>\d+)/$",views.IssueDetail,name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteIssue.as_view(),name="delete"),
    url(r"join/(?P<pk>\d+)/$",views.JoinIssue.as_view(),name="join"),
    url(r"leave/(?P<pk>\d+)/$",views.LeaveIssue.as_view(),name="leave"),   
    url(r"solve/(?P<pk>\d+)/$",views.SolveIssue,name="solve"),
    url(r"update/(?P<pk>\d+)/$",views.UpdateIssue,name="update"),  
    url(r'add_like/(?P<pk>\d+)/$', views.add_like, name='add_like'),
    url(r"accept/(?P<pk>\d+)/$", views.accept_answer, name="accept"),
    
    url(r"issues_list_api/$", views.issues_list_api, name="issues_list_api"),
    url(r"issue_detail_api/(?P<pk>\d+)/$", views.issue_detail_api, name="issue_detail_api"),
    url(r"answers_list_api/$", views.answers_list_api, name="answers_list_api"),
    

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <title>Project X1</title>
    <link rel="icon" type="image/png"
        href="https://i.pinimg.com/originals/c5/1c/da/c51cda89a29626ea7b655bd7f703218c.png" />
    <link href="{%static 'css/app.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <nav id="sidebar" class="sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="{% url 'home' %}">
                    <span class="align-middle">Project X1</span>
                </a>

                <ul class="sidebar-nav">
                    <li class="sidebar-header">
                        Pages
                    </li>

                    <li class="sidebar-item ">
                        <a class="sidebar-link" href="{% url 'home' %}">
                            <i class="align-middle" data-feather="sliders"></i> <span
                                class="align-middle">Dashboard</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="{% url 'accounts:profile' pk=user.pk %}">
                            <i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="{% url 'set' %}">
                            <i class="align-middle" data-feather="settings"></i> <span
                                class="align-middle">Settings</span>
                        </a>
                    </li>

                    <li class="sidebar-header">
                        Tools & Components
                    </li>
                    <li class="sidebar-item">
                        <a href="#ui" data-toggle="collapse" class="sidebar-link collapsed">
                            <i class="align-middle" data-feather="briefcase"></i> <span
                                class="align-middle">Projects</span>
                        </a>
                        <ul id="ui" class="sidebar-dropdown list-unstyled collapse " data-parent="#sidebar">
                            <li class="sidebar-item"><a class="sidebar-link" href="{% url 'projects:all' %}">View
                                    Projects</a>
                            </li>
                            <li class="sidebar-item"><a class="sidebar-link" href="{% url 'projects:create' %}">Create
                                    Project</a>
                            </li>
                    </li>
                </ul>
                </li>

                <li class="sidebar-item">
                    <a href="#forms" data-toggle="collapse" class="sidebar-link collapsed">
                        <i class="align-middle" data-feather="check-circle"></i> <span
                            class="align-middle">Issues</span>
                    </a>
                    <ul id="forms" class="sidebar-dropdown list-unstyled collapse " data-parent="#sidebar">
                        <li class="sidebar-item"><a class="sidebar-link" href="{% url 'issues:all' %}">View Issues</a>
                        </li>
                        <li class="sidebar-item"><a class="sidebar-link" href="{% url 'issues:create' %}">Raise Issue
                            </a></li>
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'chats:all' %}">
                        <i class="align-middle" data-feather="message-square"></i> <span
                            class="align-middle">Messenger</span>
                    </a>
                </li>

                <li class="sidebar-header">
                    Extras
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">
                        <i class="align-middle" data-feather="code"></i> <span class="align-middle">SecureChat</span>
                    </a>
                </li>


            </div>
        </nav>

        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">
                <a class="sidebar-toggle d-flex">
                    <i class="hamburger align-self-center"></i>
                </a>

                <!-- Navbar Search-->

                <form action="{% url 'search' %}" method="POST" class="form-inline d-none d-sm-inline-block">
                    {% csrf_token %}
                    <div class="input-group input-group-navbar">
                        <input name="search" type="search" class="form-control" placeholder="Search…"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn" type="submit">
                                <i class="align-middle" data-feather="search"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- -->

                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navbar-align">


                        <li class="nav-item dropdown">
                            <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#"
                                data-toggle="dropdown">
                                <i class="align-middle" data-feather="settings"></i>
                            </a>

                            <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#"
                                data-toggle="dropdown">

                                <span class="text-dark">{{user.username}}</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="{% url 'accounts:profile' pk=user.pk %}"><i
                                        class="align-middle mr-1" data-feather="user"></i> Profile</a>
                                <a class="dropdown-item" href="{% url 'home' %}"><i class="align-middle mr-1"
                                        data-feather="pie-chart"></i> Analytics</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'set' %}"><i class="align-middle mr-1"
                                        data-feather="settings"></i> Settings & Privacy</a>
                                <div class="dropdown-divider"></div>
                                {% if user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                                <a class="dropdown-item" href="{% url 'accounts:register' %}">Sign Up</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            {% block content %}


            {% endblock %}
        </div>
    </div>

    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/tagsinput.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        if ('{{message}}' != '') {
            alert('{{message}}')
        }
    </script>
    {% block script %}

    {% endblock %}

</body>

</html>

templates/dashboard.html
{% if user.is_authenticated %}
{% include 'user_dash.html' %}
{% else %}
{% include 'welcome.html' %}
{% endif %}

templates/search_result.html
{% extends 'base.html' %}
{% block content %}

<main class="content">

    <div class="container-fluid p-0">
        {% if not projects %}
        <div class="row mb-2 mb-xl-3">
            <div class="col-auto d-none d-sm-block">
                <h3><strong>No</strong> Projects with tag <strong>{{search_term.capitalize}}</strong> </h3>
            </div>
        </div>
        {% else %}
        <div class="row mb-2 mb-xl-3">
            <div class="col-auto d-none d-sm-block">
                <h3><strong>{{search_term.capitalize}}</strong> Projects</h3>
            </div>
        </div>
        <div class="w-100">
            <div class="row">

                {% for project in projects %}
                {% include "projects/_project.html" %}
                {% endfor %}

            </div>
        </div>
        {% endif %}
    </div>

    {% if not issues %}
    <div class="row mb-2 mb-xl-3">
        <div class="col-auto d-none d-sm-block">
            <h3><strong>No</strong> issues with tag <strong>{{search_term}}</strong> </h3>
        </div>
    </div>
    {% else %}

    <div class="row">
        <div class="card flex-fill">
            <div class="card-header">


                <h5 class="card-title mb-0"><strong>{{search_term}}</strong> Issues</h5>
            </div>
            <table class="table table-hover my-0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th class="d-none d-xl-table-cell">Created At</th>
                        <th class="d-none d-xl-table-cell">Created By</th>
                        <th class="d-none d-xl-table-cell">Project</th>
                        <th class="d-none d-xl-table-cell">Members Working</th>
                        <th class="d-none d-xl-table-cell">Priority</th>
                        <th class="d-none d-xl-table-cell">Deadline</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for issue in issues %}
                    {% include 'issues/_issue.html' %}
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    {% endif %}
</main>

{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<main class="content">
	<div class="container-fluid p-0">

		<h1 class="h3 mb-3">Settings</h1>

		<div class="row">
			<div class="col-md-3 col-xl-2">

				<div class="card">
					<div class="card-header">
						<h5 class="card-title mb-0">Profile Settings</h5>
					</div>

					<div class="list-group list-group-flush" role="tablist">
						<a class="list-group-item list-group-item-action active" data-toggle="list" href="#account"
							role="tab">
							Account
						</a>
						<a class="list-group-item list-group-item-action" data-toggle="list" href="#password"
							role="tab">
							Password
						</a>
						<a class="list-group-item list-group-item-action badge-danger"
							href="{% url 'accounts:deluser' %}">
							Delete account
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-9 col-xl-10">
				<div class="tab-content">
					<div class="tab-pane fade show active" id="account" role="tabpanel">

						<div class="card">
							<div class="card-header">

								<h5 class="card-title mb-0">Profile info</h5>
							</div>
							<div class="card-body">
								<img id="profileimg" src="{{profile.profile_pic}}" alt="Profile pic"
									class="rounded-circle img-responsive mt-2" width="188" height="188" /><br><br>
								<hr>
								<progress value="0" max="100" id="uploader">0%</progress>
								<input type="file" accept="image/*" value="upload" id="imgbtn" />

								<form method="POST" action="{% url 'set' %}" enctype="multipart/form-data">
									{% csrf_token %}
									{{profile_form.as_p}}
									<button type="submit" class="btn btn-primary">Save changes</button>
								</form>
							</div>
						</div>

					</div>
					<div class="tab-pane fade" id="password" role="tabpanel">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">Password</h5>

								<form method="POST" action="{% url 'changepass' %}">
									{% csrf_token %}
									{% for field in form %}
									<div class="form-group">
										<label for="inputPasswordCurrent">{{field.label_tag}}</label>
										<input type="password" name="{{field.name}}" class="form-control">
									</div>
									{% endfor %}

									<button type="submit" class="btn btn-primary">Save changes</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}
{% block script %}
<script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-storage.js"></script>
<script src="{% static 'js/firebaseconfig.js' %}"></script>

<script>
	var uploader = document.getElementById('uploader');
	var imgbtn = document.getElementById('imgbtn');
	var profile_model = document.getElementById('profile_model')

	imgbtn.addEventListener('change', function (e) {
		var file = e.target.files[0];
		var storageRef = firebase.storage().ref('profile_pic/' + '{{profile.user.pk}}.jpg');
		var task = storageRef.put(file);
		var profileid = document.getElementById('profileimg');

		task.on('state_changed',
			function progress(snapshot) {
				var percentage = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
				uploader.value = percentage;
			},
			function error(err) {

			},

			function complete() {
				var imgfileurl = firebase.storage().ref('profile_pic/').child('{{profile.user.pk}}.jpg')
					.getDownloadURL();
				imgfileurl.then(profile_url => {
					console.log(profile_url);
					profileid.src = profile_url;
					profile_model.value = profile_url;

				});
			}
		);
	});
</script>

{% endblock %}